# Generated by Django 3.0.3 on 2020-03-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('No', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(max_length=20)),
                ('classname', models.CharField(choices=[('Saber', '剑士'), ('Archer', '弓兵'), ('Lancer', '枪兵'), ('Assassin', '暗匿着'), ('Rider', '骑兵'), ('Caster', '魔术师'), ('Ruler', '裁定者'), ('MoonCancer', '月癌'), ('Avenger', '复仇者'), ('Alterego', '他人格'), ('Foreigner', '降临者'), ('Berserker', '狂战士'), ('Shielder', '盾兵')], max_length=10)),
                ('nickname', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', '男'), ('female', '女'), ('unknown', '未知')], default='female', max_length=10, verbose_name='性别')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('storyno', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('sno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faker.Servant')),
            ],
        ),
    ]
